stakwork/hive

.github/workflows/build.yml
This is a github workflow to insure that we can always run `npm run build` and have it work
=> ci: build action

docs/feature-flags.md
Simple .env-based feature flags with role-based access control architecture documentation.
Example:
- New Workflow link out feature should be for us guys only (ADMIN) but not Users
- simple .env based
=> Add feature flag documentation

prisma/schema.prisma, src/app/api/chat/message/route.ts, src/app/api/tasks/[taskId]/messages/route.ts, src/app/w/[slug]/task/[...taskParams]/page.tsx
- Add stakworkProjectId field to Task model to persist Stakwork project ID
- Store project_id from Stakwork API response in database when sending messages
- Return stakworkProjectId in task messages API response
- Auto-subscribe to logs on page load using stored project ID
Fixes issue where thinking logs wouldn't render after refresh/navigation.
=> Fix Stakwork logs not resubscribing after page refresh

src/app/api/chat/message/route.ts, src/app/api/chat/response/route.ts, src/app/w/[slug]/task/[...taskParams]/artifacts/longform.tsx
- Wrap long artifact titles with line-clamp-2
- Shows ellipsis after 2 lines instead of unlimited wrapping
- Keeps layout clean and consistent
- Maintains original text-lg size for readability
- Icon size stays fixed at h-5 w-5
=> Add line-clamp-2 to artifact titles for better layout

src/__tests__/integration/api/workspace-member-roles.test.ts, src/__tests__/unit/lib/auth/roles.test.ts, src/__tests__/utils/test-helpers.ts, src/app/api/workspaces/[slug]/members/[userId]/route.ts, src/app/api/workspaces/[slug]/members/route.ts, src/components/workspace/AddMemberModal.tsx, src/components/workspace/WorkspaceMembers.tsx, src/hooks/useWorkspaceAccess.ts, src/lib/auth/roles.ts, src/lib/constants.ts, src/lib/helpers/workspace-member-queries.ts, src/services/workspace.ts, src/types/workspace.ts
- Create centralized roles module at src/lib/auth/roles.ts using Prisma schema as single source of truth
- Replace hard-coded role arrays in API routes with isAssignableMemberRole() validation
- Update AddMemberModal to use centralized roles and Zod schemas
- Fix useWorkspaceAccess hook to eliminate duplicate role hierarchy and permission logic
- Standardize all WorkspaceRole imports to use centralized module
- Add comprehensive unit tests with 19 test cases covering all validation helpers
- Update workspace permission system to use Prisma enum consistently
Addresses inconsistent role validation patterns and establishes type-safe, maintainable role management.
=> refactor: centralize WorkspaceRole enum and shared validation

src/app/api/workspaces/route.ts
Replace getWorkspacesByUserId with getUserWorkspaces in the /api/workspaces endpoint to properly return both owned and member workspaces instead of only owned workspaces. This fixes the workspace count display in the workspace switcher dropdown.
=> fix: workspace switcher showing (0) for member workspaces

src/app/api/stakwork/create-customer/route.ts
- Change decryptField() call to use correct field type 'swarmApiKey' instead of 'stakworkApiKey'
- Rename variable from decryptedStakworkApiKey to decryptedSwarmApiKey for clarity
- Resolves issue where encrypted object was returned instead of decrypted key string
=> Fix stakwork decryption field type and variable naming

src/utils/devContainerUtils.ts
This will allow the container to spin up a tiny bit faster because it doesn't have to create a docker image of the source code, it just runs a slim alpine image sleeping indefinitely.
=> using a slim image to keep container alive

src/app/api/tests/coverage/route.ts
Changed stakgraph URL construction to properly parse swarm.swarmUrl and extract hostname instead of using swarm.name directly.
=> Fix test coverage API to use swarm URL instead of name

src/app/page.tsx, src/lib/auth/nextauth.ts, src/lib/auth/workspace-resolver.ts, src/utils/mockSetup.ts
Closes: #46 
Used Github Auth because it's needed for some functions and easy to setup. But acomplished the following to make setup easy: 
- Created and seeded the Db with mock data immediately after setup to make development easier. 
- Need to turn on `DEVELOPMENT="true"` to have your workspace seeded with Mock Data. 
- Can be easily opted out of. 
https://www.loom.com/share/2d4767604b0748f7a100ee8a8d60f5c7?sid=52940ff0-ec62-41f2-8b94-dcbcce594d8a
@Evanfeenstra @tomsmith8 please what do you think about this workflow?
=> fix: dev mode setup after authentication

src/__tests__/integration/api/swarm-authorization.test.ts, src/app/api/swarm/route.ts, src/services/workspace.ts
Add proper workspace access validation to swarm creation and update endpoints to ensure users can only manage swarms in workspaces where they have appropriate permissions.
Changes:
- Add workspace access validation to POST /api/swarm
- Add workspace access validation to PUT /api/swarm
- Restrict swarm operations to OWNER and ADMIN roles only
- Add getWorkspaceById helper function for workspace access by ID
- Add comprehensive integration tests for authorization scenarios
The changes ensure workspace isolation and prevent unauthorized swarm management while preserving existing onboarding flows.
=> Add workspace authorization to swarm API endpoints

src/app/api/workspaces/[slug]/stakgraph/route.ts, src/components/stakgraph/forms/SwarmForm.tsx
- Remove toggle between fields, show both independently
- Add show/hide toggle for API key field with eye icon on right
- Return decrypted swarmApiKey in GET endpoint for form display
- Both fields now properly managed separately as per data model
=> fix: display swarmApiKey and swarmSecretAlias as separate fields in stakgraph form

src/app/api/chat/message/route.ts, src/lib/utils.ts, src/services/task-workflow.ts
The callStakworkAPI function was incorrectly using STAKWORK_BASE_URL instead of the application's base URL for webhook callbacks. This caused webhook URLs to point to the Stakwork API instead of the application.
Changes:
- Extract getBaseUrl utility to shared location in lib/utils.ts
- Update callStakworkAPI to use getBaseUrl() for webhook URLs
- Refactor message route to use shared getBaseUrl function
- Ensure webhook URLs correctly point to application endpoints
The fix ensures webhook URLs (webhookUrl and workflowWebhookUrl) now properly use the application's base URL, matching the behavior in the existing callStakwork function.
=> Fix webhook URL bug in callStakworkAPI

src/stores/useStakgraphStore.ts, src/utils/request-manager.ts
When switching between workspaces, the Stakgraph form would briefly show data from the previous workspace before loading the new workspace data, or sometimes mix data between workspaces.
- Added workspace tracking with `currentSlug` to identify when switching between workspaces
- Implemented AbortController to cancel pending API requests when switching workspaces
- Reset the form state completely when changing workspaces
- Added validation to ensure responses for old workspaces are ignored
- Prevented race conditions by enforcing proper request cancellation
1. Create a new workspace with some Stakgraph configuration
2. Create another workspace with different configuration
3. Switch between workspaces multiple times
4. Verify that no stale data appears when switching workspaces
5. Confirm …
=> Fix Stakgraph workspace data persistence issues

src/app/api/stakwork/create-customer/route.ts
Fix local builds.
The POST function had a code path that could return undefined when the token was not present in the response, causing TypeScript build errors. Now returns a proper error response in all cases.
=> fix: ensure stakwork create-customer route always returns a Response

src/components/Sidebar.tsx, src/components/WorkspaceSwitcher.tsx
- Position Settings at bottom of sidebar with spacer
- Maintain visual separation with separator above user profile
=> Move Settings to bottom of sidebar above user profile

src/app/api/stakwork/user-journey/route.ts, src/lib/auth/utils.ts
- Add getOAuthProfile helper to fetch both access token and username in one call
- Update user journey API to send GitHub username along with access token
- Optimize database queries from 2 calls to 1 for better performance
=> feat: add GitHub username to Stakwork user journey data

src/app/w/[slug]/stakgraph/page.tsx, src/lib/auth/nextauth.ts, src/services/github/WebhookService.ts, src/stores/useStakgraphStore.ts
Added more permissions for webhook management. 
Testing on Organization private repo:
https://www.loom.com/share/6eb880ea0e8144b78ba554560be7a53e?sid=eb1ccb62-a1fc-4f80-862d-46b0302095ff
- Renders correct error when permissions are not met to create webhook (admin-level access required). 
- With admin-level access, successfully creates a webhook.
=> fix: more webhook organization level management

src/__tests__/integration/api/workspaces.test.ts, src/__tests__/integration/services/workspace.test.ts, src/__tests__/unit/components/error-display.test.tsx, src/__tests__/unit/components/workspace-switcher.test.tsx, src/__tests__/unit/services/workspace.test.ts, src/app/onboarding/workspace/wizard/wizard-steps/project-name-setup/index.tsx, src/app/workspaces/page.tsx, src/components/CreateWorkspaceDialog.tsx, src/components/WorkspaceSwitcher.tsx, src/components/onboarding/WorkspaceForm.tsx, src/components/ui/error-display.tsx, src/lib/constants.ts, src/services/workspace.ts
- Add configurable workspace limits via environment variable (default: 3)
- Implement service layer validation in createWorkspace function
- Add comprehensive unit and integration tests for limit enforcement
- Create centralized ErrorDisplay component for consistent error handling
- Improve WorkspaceSwitcher UX: disable/gray out creation when at limit
- Update workspaces page to show limit status instead of creation option
- Prevent users from entering creation flow when at limit
- Add informative messaging: '3/3 workspaces used' with clear guidance
- Ensure deleted workspaces don't count toward limit
- Test coverage: limit enforcement, deletion scenarios, cross-user isolation
=> Implement 3-workspace limit with improved UX

src/components/Sidebar.tsx
The floating burger menu in the top left corner is no longer needed on task pages since we now have a dedicated back button in the task chat view.
- Hide mobile sidebar Sheet component on task pages
- Users can navigate back using the back button in ChatArea component
=> Remove floating burger menu from task pages

src/app/api/tasks/stats/route.ts, src/components/tasks/TasksList.tsx, src/hooks/useTaskStats.ts
- Add /api/tasks/stats endpoint for efficient task statistics queries
- Create useTaskStats hook for fetching workspace task counts
- Update TasksList to use statistics API instead of filtering paginated results
- Fix counter showing only paginated results instead of total running tasks
- Counter now displays all IN_PROGRESS tasks regardless of pagination
Resolves issue where running tasks counter only showed tasks from current page (max 5) instead of the actual total count across all workspace tasks.
=> fix: show accurate running tasks counter across all pages

src/app/w/[slug]/task/[...taskParams]/artifacts/code.tsx
- Add normalizeContent helper to handle both string and object content types
- Legacy Stakwork workspaces sometimes send JSON objects (like package.json) directly in content.content
- This was causing 'Objects are not valid as a React child' errors
- Now properly stringifies objects for display and copying
=> Fix CODE artifact rendering for Stakwork legacy workspaces

src/app/api/workspaces/[slug]/tasks/notifications-count/route.ts
Only count tasks with workflowStatus IN_PROGRESS or PENDING in the notification counter, excluding completed and failed tasks
=> Fix task counter to only show active tasks

prisma/migrations/20250906015917_add_security_review_janitor/migration.sql, prisma/schema.prisma, src/app/api/workspaces/[slug]/janitors/config/route.ts, src/app/w/[slug]/insights/page.tsx, src/lib/constants/janitor.ts, src/services/janitor-cron.ts, src/types/janitor.ts
- Add SECURITY_REVIEW to JanitorType enum in Prisma schema
- Add securityReviewEnabled field to JanitorConfig model
- Update backend constants with Security Review configuration
- Update API endpoints to handle new security review field
- Update insights page to display Security Review janitor (no longer coming soon)
- Create database migration for schema changes
=> Add SECURITY_REVIEW janitor type

CLAUDE.md, src/lib/constants.ts
- Change MAX_WORKSPACES_PER_USER to NEXT_PUBLIC_MAX_WORKSPACES_PER_USER
- Required for the limit to be accessible in client components
- Fixes issue where changing the limit in production didn't affect UI
=> Fix workspace limit environment variable for client-side usage

src/app/w/[slug]/task/[...taskParams]/page.tsx
Previously, the workflow link in the task header required a hard refresh to appear after starting a task. This was because the stakworkProjectId wasn't being set when receiving the project ID from the API response.
Now sets stakworkProjectId immediately when the workflow starts, ensuring the link appears without needing a page refresh.
Fixes #574
=> fix: task header workflow link now appears immediately

src/app/w/[slug]/learn/components/LearnChatMessage.tsx
- Force prose content to use theme foreground color
- Override Tailwind's default prose styling that was causing poor contrast
- Ensures chat messages are readable in light mode
Before:
After:
=> fix: improve Learn chat message contrast in light mode (#709)

prisma/migrations/20250919131339_add_test_setup_flags_to_repository/migration.sql, prisma/schema.prisma
- Add testingFrameworkSetup flag to track if any testing framework is configured
- Add playwrightSetup flag to track Playwright installation for user journey recording
- These flags will enable recommendations for test framework setup when missing
=> feat: add test setup tracking flags to Repository model

src/lib/runtime.ts, src/services/pool-manager/PoolManagerService.ts, src/services/pool-manager/api/pool.ts, src/services/workspace.ts, src/types/pool-manager.ts
- Add deleteUser method to PoolManagerService
- Create deleteUserApi function using admin authentication
- Update workspace deletion to also delete associated pool user
- Pool user deletion uses admin credentials from environment
- Errors are logged but don't block workspace deletion
Fixes #814
=> feat: delete pool user when deleting workspace

src/app/w/[slug]/learn/components/LearnSidebar.tsx, src/components/WorkspaceSwitcher.tsx, src/components/dashboard/test-coverage-card/index.tsx, src/components/insights/CoverageInsights.tsx, src/components/insights/TestCoverageCard.tsx, src/components/ui/skeleton.tsx
- Install shadcn skeleton component
- Add skeleton to dashboard test coverage card
- Add skeleton to workspace switcher loading state
- Add skeleton to learn sidebar loading state
- Add skeleton to insights test coverage card (3 metrics)
- Standardize CoverageInsights table to use skeleton rows
Skeleton is used only for components with predictable data structures that always load content, improving UX by showing the expected layout while loading.
=> Add skeleton loading states to key components

src/__tests__/fixtures/repository.ts, src/__tests__/integration/api/auth-revoke-github.test.ts, src/__tests__/integration/api/chat-message.test.ts, src/__tests__/integration/api/chat-messages-get.test.ts, src/__tests__/integration/api/github-users-search.test.ts, src/__tests__/integration/api/repository-update.test.ts, src/__tests__/integration/api/workspace-member-roles.test.ts, src/__tests__/integration/api/workspace-members.test.ts, src/__tests__/integration/api/workspace-update.test.ts
Refactored 8 integration test files to use fixture helpers instead of raw Prisma calls:
- repository-update.test.ts
- workspace-update.test.ts
- workspace-members.test.ts
- workspace-member-roles.test.ts
- chat-message.test.ts
- chat-messages-get.test.ts
- github-users-search.test.ts
- auth-revoke-github.test.ts
Changes:
- Created new repository.ts fixture
- Replaced 13 raw Prisma create calls with fixture functions
- Net reduction: 74 lines (119 removed, 45 added)
- All 163 integration tests passing
Fixtures now consistently used across all integration tests
=> Tier 2.2: Enforce fixture-based data creation (global)

playwright.config.ts, src/lib/auth/nextauth.ts, src/utils/mockSetup.ts
Root cause: Playwright workers running in parallel were calling resetDatabase() simultaneously, causing one worker to delete another worker's mock workspace mid-authentication. This resulted in 80-90% pass rate with intermittent failures.
Changes:
- Configure Playwright to use single worker (workers: 1, fullyParallel: false)
- Wrap mock workspace creation in db.$transaction() for atomicity
- Add workspace verification in signIn callback to catch issues early
- Improve error logging in auth flow (replace empty catch blocks)
- Simplify session callback to query workspace directly vs calling helper
Result: 100% E2E test pass rate (10/10 tests passing consistently)
=> Fix E2E test flakiness by preventing parallel worker database conflicts

src/__tests__/e2e/specs/workspace/workspace-membership.spec.ts, src/__tests__/e2e/support/fixtures/e2e-scenarios.ts, src/__tests__/e2e/support/fixtures/selectors.ts, src/__tests__/e2e/support/fixtures/workspace.ts, src/__tests__/e2e/support/page-objects/WorkspaceSettingsPage.ts, src/__tests__/e2e/support/page-objects/index.ts, src/components/ui/confirm-dialog.tsx, src/components/workspace/AddMemberModal.tsx, src/components/workspace/WorkspaceMembers.tsx
Implements comprehensive E2E test coverage for the complete workspace member lifecycle including invite, role updates, persistence verification, and removal.
- Add WorkspaceSettingsPage Page Object with member management methods
- Add workspace membership E2E spec with multi-step user journey test
- Add data-testid attributes to workspace member components for reliable selection
- Add createInvitableUser scenario helper for test data setup
- Extend selectors.ts with workspace members and modal selectors
- Add confirm-dialog data-testid for removal confirmation
=> Add E2E tests for workspace member management

src/components/pool-status/index.tsx, src/services/pool-manager/PoolManagerService.ts, src/types/pool-manager.ts
Replace redundant "running" metric with "in use" and "available" breakdown. Move pending/failed to separate line with muted styling when present.
Changes:
- Primary line: "{n} in use" (green) • "{n} available" (muted)
- Secondary line: "{n} pending" (orange) • "{n} failed" (red) - only shown if > 0
- Remove "running" count (redundant: running = used + unused)
=> Improve pool status display clarity

src/services/task-coordinator-cron.ts
Modified task coordinator cron to always reserve at least 1 available pod. 
Changed check from availablePods === 0 to availablePods <= 1, ensuring recommendations are only processed when 2+ pods are available.
=> feat: reserve one available pod in task coordinator

src/components/insights/TestCoverageCard.tsx
Update coverage indicators to use more realistic thresholds:
- Green: 20%+ (previously 70%+)
- Yellow: 10-20% (previously 15-70%)
- Red: 0-10% (previously 0-15%)
=> feat: adjust test coverage color thresholds
