stakwork/hive

- docker-compose.dev.yml
@Rassl this allows the .env vars to be used and a fall back to default values
> ci: allow .env vars

- docker-compose.dev.yml
using env file for `docker-compose.dev.yml`
> docker: env file

- src/app/page.tsx
> Change home page text to 'Get Started'

- prisma/migrations/20250801100154_longform/migration.sql
- prisma/schema.prisma
- src/app/api/mock/helpers.ts
- src/app/api/mock/responses.ts
- src/app/w/[slug]/task/[...taskParams]/artifacts/index.ts
- src/app/w/[slug]/task/[...taskParams]/artifacts/longform.tsx
- src/app/w/[slug]/task/[...taskParams]/components/ChatMessage.tsx
- src/app/w/[slug]/task/[...taskParams]/page.tsx
- src/lib/chat.ts
Issue: #104 
- To add a LONGFORM artifact to the chat right after the messages.
- Make the artifact scrollable.
Remake of #107
> feature: add longform artifact

- README.md
The README was outdated and described a Lightning Network/Sphinx Chat application instead of the current workspace-based platform. This update:
- Replaces Lightning Network authentication with NextAuth.js + GitHub OAuth
- Updates tech stack to include Zustand, TanStack Query, Pusher
- Documents the multi-tenant workspace architecture with role-based permissions
- Adds comprehensive stakgraph and swarm management documentation
- Updates project structure to match current /w/[slug]/* pattern
- Includes proper setup instructions for GitHub OAuth and database
- Adds testing commands and development workflows
- Documents AI-powered chat interface and artifact generation
- Removes references to bounty system and sphinx authentication
- Adds Docker deployment and production environment …
> Update README.md to reflect current architecture

- vercel.json
this should disable vercel branch deployments
> ci: disable branch delployment

- .github/workflows/test.yml
closes https://github.com/stakwork/hive/issues/134
> ci: test workflow

- src/app/api/stakwork/webhook/route.ts
- Change mapStakworkStatus to return null for unknown statuses instead of FAILED
- Skip database update when status is unknown, preserving existing workflow status
- Add better logging for unknown status values from Stakwork
- Prevents tasks from incorrectly showing as "Failed" when they should remain "Pending"
> Fix workflow status defaulting to FAILED for unknown Stakwork statuses

- src/services/stakwork/index.ts
So we can mark the secret as stak prod on the other side
> sending source when creating secret for customer

- prisma/migrations/20250807110948_add_workflow_url_to_chat_messages/migration.sql
- prisma/schema.prisma
- src/app/api/chat/message/route.ts
- src/app/api/chat/response/route.ts
- src/app/w/[slug]/task/[...taskParams]/artifacts/longform.tsx
- src/app/w/[slug]/task/[...taskParams]/components/ChatMessage.tsx
- src/app/w/[slug]/task/[...taskParams]/components/WorkflowUrlLink.tsx
- src/app/w/[slug]/task/[...taskParams]/components/index.ts
- src/lib/chat.ts
- Add workflowUrl field to ChatMessage schema and migration
- Create WorkflowUrlLink component with hover functionality
- Update API endpoints to handle workflowUrl in requests/responses
- Add workflow URL display to chat messages and artifacts
> Add workflow URL support to ChatMessage model

- prisma/migrations/20250807110948_add_workflow_url_to_chat_messages/migration.sql
- prisma/schema.prisma
- src/app/api/chat/message/route.ts
- src/app/api/chat/response/route.ts
- src/app/w/[slug]/task/[...taskParams]/artifacts/longform.tsx
- src/app/w/[slug]/task/[...taskParams]/components/ChatMessage.tsx
- src/app/w/[slug]/task/[...taskParams]/components/WorkflowUrlLink.tsx
- src/app/w/[slug]/task/[...taskParams]/components/index.ts
- src/lib/chat.ts
> Revert "Revert "Add workflow URL support to ChatMessage model""

- src/app/settings/page.tsx
- src/app/w/[slug]/settings/page.tsx
- src/components/BackButton.tsx
- src/components/NavUser.tsx
Fixes: https://github.com/stakwork/hive/issues/278
- Separate global user settings `/settings` and workspace settings
> Refactor settings separation

- README.md
- package.json
- scripts/helpers/decrypt-and-log.ts
- scripts/seed-from-github-account.ts
> chore: db seeding scripts

- src/components/workspace/WorkspaceMembers.tsx
> Update button variant for PM role in WorkspaceMembers component

- docs/ARCHITECTURE.md
Add comprehensive architecture guide covering stack, directory layout, data model, auth, real-time, S3 uploads, external services, APIs, UI routing, testing, env, and common flows.
> docs: add architecture overview

- package.json
https://www.loom.com/share/6fc6bc0cfe4a4b06981180b0155efd37?sid=ef1ae770-011f-4abe-8dba-ae74401356ec
> Update test script in package.json to run unit and integration tests sequentially

- env.example
- prisma/migrations/20250807220247_webhooks/migration.sql
- prisma/schema.prisma
- scripts/helpers/decrypt-and-log.ts
- scripts/migrate-encrypt-existing-data.ts
- scripts/rotate-encryption-key.ts
- scripts/seed-from-github-account.ts
- src/app/api/github/webhook/ensure/route.ts
- src/app/api/github/webhook/route.ts
- src/app/api/swarm/stakgraph/ingest/route.ts
- src/app/api/swarm/stakgraph/sync/route.ts
- src/app/api/workspaces/[slug]/stakgraph/route.ts
- src/app/w/[slug]/stakgraph/page.tsx
- src/components/stakgraph/forms/ServicesForm.tsx
- src/components/stakgraph/types.ts
- src/config/services.ts
- src/lib/auth/nextauth.ts
- src/lib/encryption/field-encryption.ts
- src/lib/url.ts
- src/services/github/WebhookService.ts
- src/services/github/api/webhooks.ts
- src/services/github/index.ts
- src/services/index.ts
- src/services/swarm/stakgraph-actions.ts
- src/stores/useStakgraphStore.ts
- src/types/encryption.ts
- src/types/github.ts
- src/utils/repositoryParser.ts
Continuation of #193 and #190 
Push Commands with webhooks:
https://www.loom.com/share/393d5a3541024cef8a9b5a657e70e3ca?sid=ae194d37-a326-4d81-b789-b9a62ea893fd
Merge Pull request with webhooks:
https://www.loom.com/share/e2142ed941094b3eba307fd4db4dec1a?sid=364ea407-fe9a-49ef-8800-e96351257cca
> feature: automate graph sync

- env.example
- src/app/api/swarm/stakgraph/webhook/route.ts
- src/services/swarm/StakgraphWebhookService.ts
- src/services/swarm/index.ts
uses SwarmApikey instead of webhook_secret and refactored endpoint to use services for stakgraph
> chore: used swarmApiKey and refactored

- src/app/api/workspaces/[slug]/stakgraph/route.ts
- src/components/stakgraph/forms/SwarmForm.tsx
> Revert "fix: display swarmApiKey and swarmSecretAlias as separate fields in stakgraph form"

- src/components/insights/RecommendationsSection/index.tsx
- Fix logic to properly check only boolean toggle fields instead of all janitor config values
- Update copy to be more professional and action-oriented
- Add distinct UI states for disabled, analyzing, and complete states
- Replace settings icon with sparkles for better visual representation
- Streamline messaging by removing redundant text
> improve: enhance recommendations section UX and copy

- src/app/api/tasks/route.ts
- src/components/tasks/TaskCard.tsx
- src/hooks/useWorkspaceTasks.ts
this wasn't showing a link in the Preview on the pod, but wanted to review the quality
> Add Stakwork project links to task page

- src/__tests__/unit/services/workspace.test.ts
- src/app/workspaces/LogoutButton.tsx
- src/app/workspaces/page.tsx
- src/components/ui/toast.tsx
- src/services/workspace.ts
- Fix server-side exception on /workspaces page by optimizing getUserWorkspaces database queries
- Redesign workspaces page UI using clean shadcn components inspired by workspace switcher
- Replace broken logout redirect with proper shadcn AlertDialog confirmation modal
- Fix Toast component onOpenChange prop error causing client component issues
- Add proper workspace navigation and remove settings cog per requirements
- Update tests to support optimized database query patterns
- Improve user-friendly copy for logout confirmation dialog
Resolves production /workspaces page crashes and provides much better UX
> fix: redesign workspaces page with improved UI/UX and performance

- src/stores/useStakgraphStore.ts
When renaming a project in stakgraph, the PM2 config's cwd path was incorrectly using the editable project name instead of the actual repository name from the URL. This caused issues with dev container paths not matching the actual repository structure.
Now correctly extracts the repository name from the repository URL to ensure the working directory path always matches the actual repository name.
> fix: use repository name from URL for dev container cwd path

- src/app/w/[slug]/insights/page.tsx
- src/components/insights/JanitorSection/index.tsx
- Extended JanitorItem interface to support individual comingSoon states
- Updated JanitorSection component to handle item-level coming soon status
- Moved PR Reviews janitor from Security to Testing section
- PR Reviews now displays with "Coming Soon" badge in Testing section
Closes #420
> feat: move PR reviews from security to testing section in insights

- src/app/api/github/repository/branch/numofcommits/route.ts
- src/app/w/[slug]/page.tsx
This is my attempt at fixing some of the values on the dashboards
part of https://github.com/stakwork/hive/issues/442
> Fix dashboard

- src/app/w/[slug]/page.tsx
this is part of https://github.com/stakwork/hive/issues/442
this fixes the formatting of a field and also passes a param that was needed
> fix: fixes a few minor issues on the dashboard

- src/app/api/github/webhook/route.ts
- src/app/api/swarm/stakgraph/sync/route.ts
- src/services/swarm/StakgraphWebhookService.ts
- src/services/swarm/stakgraph-actions.ts
> fix: update repo status

- src/components/Sidebar.tsx
- src/components/WorkspaceSettings.tsx
https://www.loom.com/share/8e5f2a7a729845b3b09e3c4578f9f8f2?sid=ddc7b077-47b5-46ee-a5d3-89ce6bf06c28
> Higlight Current Tab

- .github/workflows/deploy.yml
This should deploy to vercel on release
> feat: deploy to prod on release

- prisma/schema.prisma
closes https://github.com/stakwork/hive/issues/547
> fix: add rhel-openssl-3.0.x

- src/app/api/chat/message/route.ts
- src/app/api/github/app/callback/route.ts
- src/app/api/github/app/status/route.ts
- src/app/api/github/repositories/route.ts
- src/app/api/github/repository/branch/numofcommits/route.ts
- src/app/api/github/repository/route.ts
- src/app/api/github/webhook/route.ts
- src/app/api/pool-manager/create-pool/route.ts
- src/app/api/stakwork/user-journey/route.ts
- src/app/api/swarm/stakgraph/ingest/route.ts
- src/app/api/swarm/stakgraph/sync/route.ts
- src/lib/auth/nextauth.ts
- src/lib/githubApp.ts
- src/services/github/WebhookService.ts
- src/services/task-workflow.ts
> use gh app access token for workflows"

- src/components/stakgraph/forms/ServicesForm.tsx
- src/components/stakgraph/types.ts
- src/services/swarm/db.ts
- src/utils/devContainerUtils.ts
- Add optional cwd field to ServiceDataConfig and ServiceConfig types
- Add CWD input field to ServicesForm UI
- Update devContainerUtils to use custom CWD when specified
- Allow sub-services to run from subdirectories within repository
- Better 2x2 grid UI layout
Closes #682
> feat: add CWD field for services configuration

- src/app/api/swarm/stakgraph/sync/route.ts
- src/lib/url.ts
- src/services/swarm/StakgraphWebhookService.ts
> debug: logs and callbackurl fixes

- src/app/w/[slug]/page.tsx
The test coverage functionality was accidentally removed in commit f9750a8f. This restores the display of unit, integration, and e2e test coverage percentages in the dashboard when a workspace has an active swarm.
- Re-added state management for test coverage data
- Restored API call to fetch coverage metrics
- Added loading and error states for better UX
- Display coverage percentages for all test types
> fix: restore test coverage display on dashboard

- src/__tests__/integration/api/workspaces.test.ts
- Replace 4 similar test cases with a single test.each() table-driven test
- Reduces test code by ~80 lines while maintaining all test scenarios
- Makes it easier to add new workspace creation test cases
- Keeps auth and validation tests separate for clarity
> refactor: convert workspace API tests to parameterized tests

- CLAUDE.md
- Add project overview explaining Hive's purpose and key features
- Expand tech stack to include Playwright, Zustand, Pusher, AI packages
- Add comprehensive utility scripts section (encryption, seeding, mock server)
- Document GitHub App integration flow and endpoints
- Add encryption & security section with key rotation details
- Enhance environment variables with complete list and descriptions
- Update database schema with actual model names and encrypted field format
- Add workspace-specific routes documentation
- Improve authentication flow with mock provider and token encryption details
> docs: update CLAUDE.md with current codebase architecture

- src/__tests__/setup/integration.ts
- Create src/__tests__/setup/env.ts with ensureTestEnv() helper
- Consolidate duplicate env defaults from unit.ts and integration.ts
- Remove ~40 lines of duplication across test setup files
- Maintain single source of truth for test environment variables
Part of testing infrastructure refactoring plan.
> Tier 1.2: Optimize-db-reset-

- src/__tests__/integration/services/workspace.test.ts
- Refactored workspace.test.ts to use fixture helpers
- Replaced 20 raw Prisma user creation calls with createTestUser()
- Replaced 23 ad-hoc ID/slug generations with generateUniqueSlug()
- Net reduction: ~137 lines of code
- All 163 integration tests passing
> Tier 2.2: Enforce fixture-based data creation

- playwright.config.ts
- src/__tests__/e2e/README.md
- src/__tests__/e2e/support/fixtures/auth.ts
- src/__tests__/e2e/support/fixtures/selectors.ts
- src/__tests__/e2e/support/fixtures/workspace.ts
- src/__tests__/e2e/support/helpers/assertions.ts
- src/__tests__/e2e/support/helpers/index.ts
- src/__tests__/e2e/support/helpers/navigation.ts
- src/__tests__/e2e/support/helpers/waits.ts
- src/__tests__/e2e/support/page-objects/AuthPage.ts
- src/__tests__/e2e/support/page-objects/DashboardPage.ts
- src/__tests__/e2e/support/page-objects/InsightsPage.ts
- src/__tests__/e2e/support/page-objects/TasksPage.ts
- src/__tests__/e2e/support/page-objects/index.ts
- src/components/Sidebar.tsx
- src/components/tasks/TaskCard.tsx
- src/components/ui/page-header.tsx
Establishes E2E test infrastructure foundation using the Page Object Model pattern.
**Note**: This PR contains only infrastructure - no test files yet. Tests will be added in follow-up PRs after database fixtures are ready.
- **Support structure**: Created `support/` directory with fixtures, page objects, and helpers
- **Centralized selectors**: Added `selectors.ts` for DRY selector management  
- **Playwright config**: Configured for parallel execution, CI/CD, and better reporting
- **Comprehensive README**: Best practices, usage examples, and migration guide
- `AuthPage`: Authentication flows and session management
- `DashboardPage`: Dashboard navigation and component verification
- `TasksPage`: Task creation, chat, and list operations
- `InsightsPage`: Janitor recommendations and …
> E2E Test Infrastructure with Page Object Model

- src/__tests__/unit/lib/ai/utils.test.ts
- src/__tests__/unit/lib/base-service.test.ts
- src/__tests__/unit/lib/chat.test.ts
- src/__tests__/unit/lib/constants.test.ts
- src/__tests__/unit/lib/constants/janitor.test.ts
- src/__tests__/unit/lib/db.test.ts
- src/__tests__/unit/lib/env-parser.test.ts
- src/__tests__/unit/lib/icons.test.tsx
- src/__tests__/unit/lib/modal.test.ts
- src/lib/icons.tsx
This PR adds unit test coverage to the files in `src/lib`
> Add missing unit tests for uncovered files in src/lib

- prisma/migrations/20251007212113_add_ignore_dirs_to_repository/migration.sql
- prisma/schema.prisma
- src/app/api/tests/coverage/route.ts
- src/app/api/tests/nodes/route.ts
- src/components/insights/CoverageInsights.tsx
- src/components/insights/TestCoverageCard.tsx
- src/components/ui/skeleton.tsx
- src/hooks/useCoverageNodes.ts
- src/lib/helpers/repository.ts
- src/types/stakgraph.ts
- src/types/test-coverage.ts
-https://www.loom.com/share/8781a16df827405da8cb1c81981edfe1?sid=362357b5-b46a-4f43-b99a-ddbfa7492c31
> fix: nodes UI
